name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: test

    steps:
    - name: Deploy to Staging
      run: echo "Deploying to staging environment..."

      notify:
        runs-on: windows-latest
        needs: deploy
    
        steps:
        - name: Send Notification
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: ${{ secrets.SMTP_SERVER }}
            server_port: ${{ secrets.SMTP_PORT }}
            username: ${{ secrets.SMTP_USERNAME }}
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: "CI/CD Pipeline Notification"
            to: ${{ secrets.RECIPIENT_EMAIL }}
            from: ${{ secrets.SMTP_USERNAME }}
            body: |
              The CI/CD pipeline has completed.
              - Build: ${{ job.status }}
              - Tests: ${{ job.status }}
              - Deploy: ${{ job.status }}
    
